# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build . -t docker_test
  displayName: 'build Docker container'

- script: docker image tag docker_test:latest $(dockerRegistry)/docker_test:latest
  displayName: 'tag Docker container'

- task: Docker@2
  inputs:
    containerRegistry: 'opennetlab azure container registry'
    repository: 'docker_test'
    command: 'push'
    tags: 'latest'